#!/bin/bash

# Install Docker
step_1()
{
  sudo apt update
  sudo apt install apt-transport-https ca-certificates curl software-properties-common
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
  sudo apt update
  apt-cache policy docker-ce
  sudo apt install docker-ce
  sudo systemctl status docker
}

# Configuring Docker command without sudo
step_2()
{
  sudo usermod -aG docker ${USER}
  su - ${USER}
  id -nG
  sudo usermod -aG docker username
}

main()
{
  step_1
  step_2
}
main