#!/bin/bash

install_packages() {
  sudo apt install vim -y --no-upgrade
  sudo snap install code --classic
}

install_packages_for_review() {
  sudo apt-get install check -y
  sudo apt-get install lcov -y
  sudo apt install gcovr -y
  sudo apt install doxygen -y
  sudo apt install libncursesw5-dev gcc make -y
}

install_docker() {
  sudo apt install apt-transport-https ca-certificates curl software-properties-common
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
  sudo apt update
  apt-cache policy docker-ce
  sudo apt install docker-ce
  sudo systemctl status docker

  sudo usermod -aG docker ${USER}
  su - ${USER}
  id -nG
  sudo usermod -aG docker username
}

install_postgresql() {
  sudo sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  sudo apt-get update
  sudo apt-get -y install postgresql
  sudo apt-get -y install postgresql-16

  sudo systemctl status postgresql
  sudo systemctl start postgresql
  sudo -u postgres psql
  # CREATE USER ваш_пользователь WITH PASSWORD 'ваш_пароль';
}


main() {
  sudo apt update
  sudo apt upgrade

  install_packages
  install_packages_for_review
  install_docker
  install_postgresql

  sudo apt autoremove
  reboot
}

main
