#!/bin/bash

install_packages() {
  sudo apt install vim -y --no-upgrade
  sudo snap install code --classic
}
install_packages_for_review() {
  sudo apt-get install check -y
  sudo apt-get install lcov -y
  sudo apt install gcovr -y
}

install_docker() {
  sudo apt install apt-transport-https ca-certificates curl software-properties-common
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
  sudo apt update
  apt-cache policy docker-ce
  sudo apt install docker-ce
  sudo systemctl status docker

  sudo usermod -aG docker ${USER}
  su - ${USER}
  id -nG
  sudo usermod -aG docker username
}


main() {
  sudo apt update
  sudo apt upgrade

  install_packages
  install_packages_for_review
  install_docker

  sudo apt autoremove
  reboot
}

# main
install_packages_for_review