#!/bin/bash

readonly USER_NAME=$(whoami)
readonly REVIEWS_FOLDER="/home/${USER_NAME}/Reviews"
readonly CURRENT_TIME=$(date +"%Y-%m-%d_%H:%M")

main() {
  source ./settings.conf
  local full_path=${REVIEWS_FOLDER}/${PEER_NAME}/${PROJECT_NAME}/${CURRENT_TIME}

  mkdir -p ${full_path}
  cd ${full_path}
  git clone ${1}
  
  local project_folder=$(ls)
  cd ${project_folder}
  git switch develop

  if [[ ${NEED_MINIVERTER} -eq 1 ]]; then
    cd materials/build/
    run.sh
    code ../../src
  else
    code ./src
  fi
}

main ${1}